### ISSUE TITLE
Cannot add OpenAI API Key

### ISSUE THREAD

**Issue by hckhanh** [askorama/orama#655] opened 2024-03-03 23:51 UTC
### Describe the bug

I cannot input the OpenAI API Key on my dashboard.
 
![image](https://github.com/askorama/orama/assets/6380436/4fa0c40b-3dbb-4885-8c37-d0377f1b544f)

### To Reproduce

1. Open Orama Cloud account
2. Enter the OpenAI API Key

### Expected behavior

I can add the key

### Environment Info

```bash
OS: MacOS 14.3.1
```

### Affected areas

Initialization, Data Insertion, Search

### Additional context

Oram Cloud

**Comment by hckhanh** [comment] 2024-03-03 23:59
Additionally, I want to set the restriction key, not all permission key. Which necessary permissions I need to create the key?

**Comment by micheleriva** [comment] 2024-03-04 00:07
Hi @hckhanh, we'll dig into that. Let me add my colleagues @allevo and @g-francesca to the conversation. Just in case, I'd recommend you to join our Slack support channel at https://orama.to/slack in case we need to ask for your email for triaging this (and keep it private)

**Comment by hckhanh** [comment] 2024-03-04 02:05
Thank you @micheleriva.

I can add the key right now, I figured out the least permissions for the key to work

![image](https://github.com/askorama/orama/assets/6380436/10a99450-a793-42c8-aadd-87e4e14308a6)

**Comment by allevo** [comment] 2024-03-04 09:35
Hi! thanks for opening this issue.
If I understood correctly the problem is to set the correct permission for the OpenAI api key. Orama should require only read to model + embeddings. We probably omitted from the documentation, we have to fix it!

If the issue is resolved, can I close this issue?

**Closed** 2024-03-04 10:19 UTC

**Comment by allevo** [comment] 2024-03-04 10:27
We use:
- the /v1/models API to check if the APIKEY is correct. This is made during the insertion
-  the /v1/embeddings API to calculate the embeddings. This is made during the deployment
So, both are required.
