### ISSUE TITLE
tsconfig with module option set to Node16 orama refuses to import 

### ISSUE THREAD

**Issue by gabrielsantosblanchet** [askorama/orama#703] opened 2024-04-18 19:07 UTC
### Describe the bug

when using tsconfig option 
"module": "Node16",
"moduleResolution": "Node16"
in a commonJS project orama refuses to import correctly 

I'm using these option as per the documentation set  in https://www.typescriptlang.org/docs/handbook/modules/reference.html#the-module-compiler-option

### To Reproduce

the code will not work, as in it doesn't event compile

### Expected behavior

since orama emits cjs file it should just be able to import the correct one

### Environment Info

```bash
windows: 11
typescript: 5.4.3
node: v18.20.2
orama: 1.2.11
```

### Affected areas

Environment/OS

### Additional context

if needed I can provide more details when asked

**Comment by shubh2336** [comment] 2024-04-29 03:07
Faced the same issue, got it working by dynamic import (as a workaround).

```
const searchFunction = async (data) => {
  return import("@orama/orama").then(async (module) => {
    const searchDB = await module.create({
      schema: { ... }
    });

    // Implement search logic below
  })
};
```

**Comment by micheleriva** [comment] 2024-09-10 22:22
@matijagaspar, @allevo, can we do something to make this less painful?

**Comment by allevo** [comment] 2024-10-16 15:15
Not able to reproduce.

`package.json`
```json
{
  "name": "removeme",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@orama/orama": "^1",
    "typescript": "^5.6.3"
  }
}

```

`index.ts`
```ts
import { create } from '@orama/orama'

const db = await create({
    schema: {
        model: 'string',
        title: 'string',
    } as const,
});
```

`tsconfig.json`
```ts
{
    "compilerOptions": {
        "module": "Node16",
        "moduleResolution": "Node16"
    }
}
```

The above code works and `tsc` compiles it.

I'm closing due to insufficient information. Feel free to open a new issue with a minimal reproducible example.

**Closed by allevo** 2024-10-16 15:15 UTC
