### ISSUE TITLE
Docusaurus V3 plugin not working on fresh install

### ISSUE THREAD

**Issue by dusanbobicic** [askorama/orama#728] opened 2024-06-03 12:37 UTC
### Describe the bug

First we tried integrating the OSS version of the plugin on the existing solution instead of lunr search plugin but we got an error. To verify that the issue is with the orama plugin we've tried on a fresh docusaurus project and it did not work. We are getting some react errors.
See the image below:
![image](https://github.com/askorama/orama/assets/9326334/2340f3a9-79e1-4710-94e3-cba5d05d3e6e)

[Error link](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=)

When we run the website in development mode using: `npm run start` We get a following error which describes more the minified issue:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `OramaSearchWithDocs`.
```
Thanks for taking your time!

### To Reproduce

1. Initialize fresh docusaurus project. It will create a docusaurus **3.4.0** site
2. Build the website, to verify that docusaurus works. It works.
3. Clear the build and cache folders
4. Install orama docusaurus V3 plugin
5. Add the plugin to docusaurus.config.ts
6. Run `npm run build`
7. Run `npm run serve`

### Expected behavior

Site is built and docusaurus website is rendered with search box.

### Environment Info

```bash
OS: Windows 11
Node: v20.10.0
Orama Plugin Version: 2.0.19
Docusaurus: 3.4.0
```

### Affected areas

Initialization, Search

**Comment by avb-is-me** [comment] 2024-06-06 18:58
@dusanbobicic hopefully a fix gets pushed soon, but I got it to work with npm run swizzle.

 I was able to get orama working with docusaurus 3.4.0, by using npm swizzle and ejecting: and then i updated @orama/searchbox, and then setting @orama/searchbox in my package.json to an older version at `1.0.0-rc33`
 
 
<img width="270" alt="Screenshot 2024-06-06 at 2 57 43 PM" src="https://github.com/askorama/orama/assets/104213687/4e12296d-056a-4348-9d91-1f9bfe6fe29c">

**Comment by madlitz** [comment] 2024-07-10 23:27
I also tried a fresh OSS install on MacOS and got this error,
`Error: ENOENT: no such file or directory, open ... /.docusaurus/orama-search-index-current.json.gz`

Also the docs are lacking on how to integrate frontend SDKs like `orama/searchbar`

**Comment by sergiocastro95** [comment] 2024-07-11 15:39
@madlitz  I got the same error 
`Error: ENOENT: no such file or directory, open ... /.docusaurus/orama-search-index-current.json.gz`
### To reproduce
Inside docusaurus exising project install:

`yarn add @orama/plugin-docusaurus-v3`

in `docusaurus.config.js` file:
`
{
  // ...
  plugins: ["@orama/plugin-docusaurus-v3"],
  // ...
}
`
After this steps, `yarn build` command doesn't work.
Anyone know what's wrong?

**Comment by thinkh** [comment] 2024-07-17 07:01
Is there any news or new version that fixes this issue?

**Comment by ShogunPanda** [comment] 2024-07-19 10:33
About the missing `index.gz`, I think the problem is here:

https://github.com/askorama/orama/pull/740/files#diff-1e5bb5e22e25889194584b9af13cb63f027762f1519cc0bf3c4b21ca15f6b866L56

**Comment by madlitz** [comment] 2024-07-24 12:22
Can confirm this is now fixed as of `2.0.20`.

The docs don't say it specifically but you need to run:

`npm run build` first 
... then 
`npm run start` or `npm run serve`

The only bug I could see is that search results are not returning fragments which I have raised an issue #751

**Comment by LevGolumov** [comment] 2024-07-27 09:19
I still get the `Error: ENOENT: no such file or directory, open ... /.docusaurus/orama-search-index-current.json.gz`

Docusaurus: 3.4.0
Orama plugin: 2.0.22

I use yarn. I tried to build first, but it still shows that error. What am I doing wrong and how can I fix that?

**Comment by madlitz** [comment] 2024-07-27 10:46
@LevGolumov Yeah when I said I confirmed it was fixed I accidentally left in a modified version of the file. I have the working fix in the PR above.

**Comment by madlitz** [comment] 2024-07-27 10:57
Also I removed the 'Orama AI' section with this css in my project:
```
div[class^="ShowSummaryCTA"] {
  display: none !important;
}
```
But it would be nice for the plugin to do this automatically. Unfortunately it looks like `@orama/searchbox` frontend code isn't included in this repo. I can only find the npm package that has already been minified.

**Comment by segevfiner** [comment] 2024-08-12 15:28
Hit this while searching for an offline search plugin for Docusaurus... :(

**Comment by jeevanjoseph** [comment] 2024-08-28 16:21
I'm also getting this `Error: ENOENT: no such file or directory, open ... /.docusaurus/orama-search-index-current.json.gz`
when I'm trying to use the plugin.

**Closed** 2024-09-04 16:02 UTC
